#!/bin/sh
set -e
set -u

find_sink_no() {
    pactl list sink-inputs | awk '
/\tSink: / {SINK=$2}
/\t\tmedia.name = "Spotify"/ {exit}
END {print SINK}
'
}

find_sink_name() {
    pactl list short sinks | awk -v SINK="$(find_sink_no)" '
$1 ~ SINK { print $2 }
'
}

monitor() {
    dbus-monitor | awk '
function report() {
    if (STATE != LAST_STATE) {
        print STATE
        fflush()
        LAST_STATE=STATE
    }
}

/spotify:track:/ {
    STATE="SONG"
    report()
}
/spotify:ad:/ {
    STATE="AD"
    report()
}
'
}

SINK="$(find_sink_name)"

while [ $# -gt 0 ]; do
    ARG="$1"
    shift
    case "$ARG" in
        -s|-sink)
            SINK="$1"
            shift
            ;;
        *)
            printf 'Unrecognized argument: %s\n' "$ARG"
            exit 1
            ;;
    esac
done

printf 'Sink is %s\n' "$SINK"

monitor | while read -r STATUS; do
    if [ "$STATUS" = "AD" ]; then
        printf 'Muting sink %s\n' "$SINK"
        pactl set-sink-mute "$SINK" 1
    elif [ "$STATUS" = "SONG" ]; then
        printf 'Unmuting sink %s\n' "$SINK"
        pactl set-sink-mute "$SINK" 0
    fi
done
